name: Build and deploy feature

on:
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GIT_BRANCH: ${{ github.head_ref }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn

      - name: Populate .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo $ENV_FILE | base64 --decode > .env

      - name: Install app dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Build Application
        run: yarn build
